name: Merge Lists

on:
  push:
    branches: [ 'main' ]

jobs:
  merge-lists:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Merge Lists
      run: python merge_lists.py
    - name: Upload Merged List
      run: |
        curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: text/plain" \
          -d "@merged_list.list" \
          https://uploads.github.com/repos/${{ github.repository }}/contents/merged_list.list
