name: Merge Lists

on:
  push:
    branches: [ 'main' ]

jobs:
  merge-lists:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Merge Lists
      run: python merge_lists.py
    - name: Upload Merged List
      uses: actions/upload-artifact@v3
      with:
        name: merged_list
        path: merged_list.list
